export const GET_LOGIN_USER = 'GET_LOGIN_USER';
export const GET_LOGIN_USER_SUCCESS = 'GET_LOGIN_USER_SUCCESS';
export const GET_LOGIN_USER_FAIL = 'GET_LOGIN_USER_FAIL';
export const RESET_LOGIN_USER = 'CLEAR_CURRENT_USER';

export const GET_LOGIN_USER_IMG = 'GET_LOGIN_USER_IMG';
export const GET_LOGIN_USER_IMG_SUCCESS = 'GET_LOGIN_USER_IMG_SUCCESS';
export const GET_LOGIN_USER_IMG_FAIL = 'GET_LOGIN_USER_IMG_FAIL';

export const GET_USER_TODO_ITEMS = 'GET_USER_TODO_ITEMS';
export const GET_USER_TODO_ITEMS_SUCCESS = 'GET_USER_TODO_ITEMS_SUCCESS';
export const GET_USER_TODO_ITEMS_FAIL = 'GET_USER_TODO_ITEMS_FAIL';
