export const GET_CURRENT_USER = 'GET_CURRENT_USER';
export const GET_CURRENT_USER_SUCCESS = 'GET_CURRENT_USER_SUCCESS';
export const GET_CURRENT_USER_FAIL = 'GET_CURRENT_USER_FAIL';
export const RESET_CURRENT_USER = 'CLEAR_CURRENT_USER';

export const GET_USER_TODO_ITEMS = 'GET_USER_TODO_ITEMS';
export const GET_USER_TODO_ITEMS_SUCCESS = 'GET_USER_TODO_ITEMS_SUCCESS';
export const GET_USER_TODO_ITEMS_FAIL = 'GET_USER_TODO_ITEMS_FAIL';
